- formulae/search/Search.py
- tests/test_data/advanced_search/__mocks__/_search/corpus=all&field=lemmas&q=vir+venerabilis&fuzziness=0&in_order=False&year=0&slop=0&month=0&day=0&year_start=0&month_start=0&day_start=0&year_end=0&month_end=0&day_end=0&date_plus_minus=0&exclusive_date_range=False_ids.json
- tests/test_data/advanced_search/__mocks__/_search/corpus=all&field=lemmas&q=vir+venerabilis&fuzziness=0&in_order=False&year=0&slop=0&month=0&day=0&year_start=0&month_start=0&day_start=0&year_end=0&month_end=0&day_end=0&date_plus_minus=0&exclusive_date_range=False_req.json
- tests/test_data/advanced_search/__mocks__/_search/corpus=all&field=lemmas&q=vir+venerabilis&fuzziness=0&in_order=False&year=0&slop=0&month=0&day=0&year_start=0&month_start=0&day_start=0&year_end=0&month_end=0&day_end=0&date_plus_minus=0&exclusive_date_range=False_resp.json
- tests/test_routes.py
> Fixed problem with multiword lemma searches not highlighting

- formulae/app.py
- tests/test_routes.py
This speeds up, e.g., get_passage 10x.
This will also certainly make the load time for the app much longer since it will always parse all of the texts every time it starts.
> Removed resolver cache

- assets/css/theme.css
- formulae/nemo.py
- templates/main/multipassage.html
- templates/main/notes.html
- templates/main/text_container.html
- templates/main/version_menu.html
This should make the option more obvious to users
> Moved the add text menus on the reading page under the titles

- assets/css/theme.css
- formulae/nemo.py
- formulae/search/routes.py
- templates/main/contact.html
- templates/main/navbar.html
- templates/search/advanced_search.html
- templates/search/search.html
- tests/test_routes.py
- Search statistics link should be more obvious
- Changes to ordering of results:
- Ordering by collection will always be ascending
- Can now order ascending or descending according to the terminus post quem or terminus ante quem
- Added "Kontakt" page for users to inform users how to suggest upgrades
> Implemented team suggestions for the search page

- assets/css/theme.css
- formulae/search/routes.py
- templates/search/search.html
- tests/test_routes.py
Also small redesign of the 'subtitle' for the search results page
> Result limitation dropdown now only shows corpora with hits

- assets/css/theme.css
- assets/js/advanced_search.js
- formulae/search/Search.py
- templates/search/advanced_search.html
- Default is now that the letters in the issued at search box must occur at the beginning of the place name for it to show up in the suggestions
- But the user can turn this off and then the letters can show up anywhere in the place name
> Composition place suggestion changes

- assets/js/empty.js
- config.py
- formulae/auth/routes.py
- formulae/nemo.py
- templates/main/navbar.html
- tests/test_routes.py
The normal link, however, does not refresh the current page automatically and, thus, it will not show the new language until the user refreshes the page.
> Manual language choice now works with JS

- formulae/app.py
- formulae/auth/routes.py
- formulae/errors/handlers.py
- formulae/nemo.py
- formulae/search/routes.py
- tests/test_routes.py
- current nemo instance is now saved in the current_app config. 
- This allows the instance to be called without having to reimport nemo every time. 
- This makes the app more modular since the different modules now depend on the app and not a specific instantiation of the app.
> More modular

- formulae/nemo.py
Maybe this will help the static assets to always be loaded
> Added max-age header for static assets

- tests/test_routes.py
They should now also work on Travis
> Edited the simple search form tests to work with WTForms 2.2.1

- formulae/search/Search.py
- tests/test_data/advanced_search/__mocks__/_search/all&text&&0&False&0&0&0&0&700&0&0&800&0&0&0&True&&urn&_resp.json
- tests/test_data/advanced_search/__mocks__/_search/all&text&&0&False&0&0&0&0&700&10&0&800&10&0&0&True&&urn&_resp.json
- tests/test_data/advanced_search/__mocks__/_search/all&text&&0&False&0&0&0&0&800&12&25&820&12&25&0&True&&urn&_ids.json
- tests/test_data/advanced_search/__mocks__/_search/all&text&&0&False&0&0&0&0&800&12&25&820&12&25&0&True&&urn&_req.json
- tests/test_data/advanced_search/__mocks__/_search/all&text&&0&False&0&0&0&0&800&12&25&820&12&25&0&True&&urn&_resp.json
- tests/test_routes.py
It should now work when the start and end dates have the same day and month.
> Corrected exclusive search

- formulae/search/Search.py
This allows all hits to be saved and thus highlighted when one chooses them
> Increased number of results saved in the session token.

- assets/css/theme.css
- components/epidoc.xsl
- formulae/nemo.py
- templates/main/multipassage.html
Also some changes to navigation possibilities in the viewer pane
> Changes to styling to show the text styles in the transcriptions

- .gitignore
- assets/css/text_container.css
- assets/js/text_container.js
- templates/main/text_container.html
added also in Gitirnore the .idea folder with the PyCharm workspace data
> Buttons to collapse the Sidebars left and right

- assets/css/theme.css
- assets/js/text_container.js
- components/epidoc.xsl
- templates/main/text_container.html
Some small changes in the styling of the reading page that should make the hiding and revealing of the left and right columns more obvious.
> Reading page styling

- formulae/nemo.py
Also corrected an error with the display of certain charter work names in the corpus view
> Added Mittelrheinische Urkunden

- formulae/nemo.py
- templates/main/sub_collection_mv.html
- tests/test_routes.py
Also made the single cards a bit more compact
> Added the regesten to the corpus_m view

- formulae/search/Search.py
- tests/test_routes.py
When the inflected and lemmatized texts are the same length, the highlighting from the lemmas will be transferred to the inflected text
> Transfer highlighting from lemmas to text

- assets/css/theme.css
- assets/js/multipassage.js
- components/epidoc.xsl
- templates/main/fulda_d1_desc.html
- templates/main/multipassage.html
- templates/main/navbar.html
Andere Texte in the navbar is now Urkunden + Briefe. Linked paragraphs now flash grey.
> Urkunden briefe

- components/xml_to_pdf.xsl
- formulae/nemo.py
Changes discussed to the downloadable PDF files have been made.
> Correct pdf

- formulae/nemo.py
- tests/test_data/formulae/data/stgallen/wartmann0001/stgallen.wartmann0001.lat001.xml
Also added a test for this case
> Corrected an error that resulted because references are now tuples

- .travis.yml
- formulae/nemo.py
- tests/test_data/formulae/data/elexicon/abbas_abbatissa/__cts__.xml
- tests/test_data/formulae/data/stgallen/wartmann0001/stgallen.wartmann0001.lat001.xml
> Error Correction

- formulae/nemo.py
- tests/test_routes.py
This should allow more fine-grained control in Varnish
> Changed the Cache-Control header in the response

- formulae/nemo.py
The only thing this slows down now is downloading search results. I will need to add some sort of progress bar or circle to that so that the user does not give up.
> No longer holding all document term vectors in memory

- formulae/nemo.py
- tests/test_routes.py
Changes to make sure that a simple lemma search is correctly highlighted in the reading screen
> Simple lemma no highlight

- assets/css/theme.css
- assets/js/advanced_search.js
- formulae/nemo.py
- formulae/search/forms.py
- templates/main/manuscript_siglen.html
- templates/main/navbar.html
- templates/main/sub_collections.html
- templates/search/advanced_search.html
- tests/test_routes.py
- The add collection screen now shows the list of collections like they are in the charter dropdown, i.e., __place__: title
- Also added the page with the lists of the manuscript siglen
> Fix add collection

- assets/js/text_container.js
- templates/main/multipassage.html
- templates/main/text_container.html
First are the reading row handles.
> Made all resize handles focusable and operable with the keyboard

- formulae/search/Search.py
- tests/test_routes.py
> Corrected a problem with total number of hits showing wrong

- templates/main/elex_collection.html
- templates/main/multipassage.html
- templates/main/sub_collections.html
Also corrected the problem with the titles on the Lexicon and Charter collections pages
> Now possible to go to next and previous MS Images

- formulae/nemo.py
- tests/test_routes.py
> Added code so that non-open texts are correctly hidden

- assets/js/advanced_search.js
- templates/search/advanced_search.html
Needs to be tested on dev for a bit
> Beta styling for the new advanced search is finished

- assets/css/theme.css
- templates/main/text_container.html
Added code so that Platzhalter won't be shown in the public Werkstatt
> No placeholders

- components/epidoc.xsl
Italicize latin words in the E-Lexicon entries
> Italic elex

- formulae/nemo.py
- tests/test_data/formulae/data/andecavensis/form002/andecavensis.form002.lat001.xml
It will see if the problem is the the json.loads conversion
> This is for testing purposes

- formulae/nemo.py
- templates/main/sub_collection.html
bf:status must == 'deperditum'
> Made the way of recognizing deperdita more precise

- formulae/nemo.py
- formulae/search/Search.py
- formulae/search/forms.py
- templates/main/sub_collections.html
Also an update to the search form for new WTForms version
> Code to add Karlmann charters

- assets/js/multipassage.js
> Removed the highlighting of words associated with notes

- templates/main/sub_collection.html
Change to sub_collection template to deal with this change
> Marculf Ergänzungen is now Marculf Ergänzung

- config.py
- formulae/__init__.py
- formulae/search/Search.py
- tests/test_routes.py
Also added the "hosts" keyword argument in ES initiation lines. This is to deal with the fact that positional arguments will be removed in a future ES-Python release.
> Added ability to have multiple ES nodes for the ES server

- assets/css/theme.css
- assets/js/text_container.js
This is to prepare for Franziska's results
> Changed underlining for formulaic parts
